project:
  type: website
  preview:
    port: 5432
  render:
    - "./*.qmd"
    - "tutorials/*/*.qmd"
    - "*.qmd"

website:
  title: "PyCon 2025"
  description: "Come check out the tools Posit, PBC has to offer at PyCon 2025."
  site-url: https://posit-dev.github.io/pycon2025-labs
  draft-mode: unlinked

  page-footer: |
    <a href="https://posit-dev.github.io/pycon2025-labs">Posit@PyCon2025</a>


  repo-url: https://github.com/posit-dev/pycon2025-labs
  repo-subdir: website
  repo-actions: [edit, issue]

  navbar:
    left:
      - text: Labs
        href: tutorials/shiny/shiny-express.qmd

    right:
      - setup.qmd
      - about.qmd

  sidebar:
    - id: labs
      style: docked
      type: light
      background: light
      foreground: dark
      contents:

        - section: "Shiny Dashboards"
          contents:
            - auto: tutorials/shiny/*.qmd
            - href: tutorials/connect/deploy-shiny.qmd

        - section: "Quarto Documents"
          contents:
            - tutorials/quarto/index.qmd
            - auto: tutorials/quarto/*.qmd

        - section: "Connect Cloud"
          contents:
            - auto: tutorials/connect/*.qmd

        - section: "Positron IDE"
          contents:
            - auto: tutorials/positron/*.qmd

        # - section: "Our F/OSS Tools"
        #   contents:
        #     - tutorials/foss/index.qmd
        #     - auto: tutorials/foss/*.qmd

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true
    toc-expand: 2

filters:
  - shinylive
  - line-highlight

editor:
  render-on-save: true

execute:
  warning: false
