project:
  type: website
  preview:
    port: 5432
  render:
    - "./*.qmd"
    - "tutorials/*/*.qmd"
    - "*.qmd"

website:
  title: "PyCon 2025"
  description: "Come check out the tools Posit, PBC has to offer at PyCon 2025."
  site-url: https://posit-dev.github.io/pycon2025-labs

  page-footer: |
    <a href="https://posit-dev.github.io/pycon2025-labs">Posit@PyCon2025</a>


  repo-url: https://github.com/posit-dev/pycon2025-labs
  repo-subdir: website
  repo-actions: [edit, issue]

  navbar:
    left:
      - text: Shiny Dashboards
        href: tutorials/shiny/shiny-express.qmd

      - text: Quarto Publishing
        href: tutorials/quarto/index.qmd

      - text: Positron IDE
        href: tutorials/positron/index.qmd

      - text: F/OSS Tools
        href: tutorials/foss/index.qmd

      - text: Connect Cloud Deployment
        href: tutorials/connect/index.qmd

    right:
      - about.qmd

  sidebar:
    - id: shiny
      style: docked
      type: light
      background: light
      foreground: dark
      contents:
        - auto: tutorials/shiny/*

    - id: oss
      style: docked
      type: light
      background: light
      foreground: dark
      contents:
        - tutorials/foss/index.qmd
        - auto: tutorials/foss/*
format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true
    toc-expand: 2

filters:
  - shinylive
  - line-highlight

editor:
  render-on-save: true

execute:
  warning: false
